accounts/urls.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.views.generic import CreateView

urlpatterns = [
    path("login/", LoginView.as_view(
        redirect_authenticated_user=True,
        template_name="accounts/login.html"
    ), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", CreateView.as_view(
        template_name="accounts/signup.html",
        form_class=UserCreationForm,
        success_url="/"
    ), name="signup"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

from recommendations import views

urlpatterns = [
    path("", views.top, name="top"),
    path('admin/', admin.site.urls),
    path("recommendations/", include("recommendations.urls")),
    path("accounts/", include("accounts.urls")),
]

recommendations/urls.py
from django.urls import path

from recommendations import views

urlpatterns = [
    path("style/regist/", views.regist_style, name="regist_style"),
    path("style/<int:style_id>/", views.detail_style, name="detail_style"),
    path("style/<int:style_id>/edit/", views.edit_style, name="edit_style"),
    path("brand/regist/", views.regist_brand, name="regist_brand"),
    path("brand/<int:brand_id>/", views.detail_brand, name="detail_brand"),
    path("review/<int:brand_id>/", views.review, name="review"),
]

accounts/models.py
from django.db import models

# Create your models here.

recommendations/models.py
from django.conf import settings
from django.db import models
from django.core.validators import MinValueValidator

class BeerStyle(models.Model):
    name = models.CharField("ビアスタイル", max_length=15)
    birth_place = models.CharField("発祥地", max_length=10)
    fermentation = models.IntegerField(
        "発酵方法", choices=((1,"上面発酵"),(2,"下面発酵"))
    )
    description = models.TextField("説明")

    def __str__(self):
        return self.name

class BeerBrand(models.Model):
    name = models.CharField("ビール銘柄", max_length=15)
    degree = models.FloatField("アルコール度数", validators=[MinValueValidator(0)])
    color = models.CharField("ビールの色", max_length=10)
    bitterness = models.FloatField("IBU", validators=[MinValueValidator(0)])
    style = models.ForeignKey(BeerStyle, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class BeerReview(models.Model):
    review = models.TextField("ユーザの感想")
    review_to = models.ForeignKey(
        BeerBrand, 
        verbose_name="感想対象", on_delete=models.CASCADE
    )
    reviewed_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name="投稿者", on_delete=models.CASCADE
    )
    reviewed_at = models.DateTimeField("投稿日", auto_now_add=True)
    updated_at = models.DateTimeField("更新日", auto_now=True)

    def __str__(self):
        return self.review_to.name + "に対する" + self.reviewed_by.username + "の感想"

recommendations/forms.py
from django import forms

from recommendations import models

class BeerStyleForm(forms.ModelForm):
    class Meta:
        model = models.BeerStyle
        fields = ("name", "birth_place", "fermentation", "description")

class BeerBrandForm(forms.ModelForm):
    class Meta:
        model = models.BeerBrand
        fields = ("name", "degree", "color", "bitterness", "style")

class ReviewForm(forms.ModelForm):
    class Meta:
        model = models.BeerReview
        fields = ("review",)

accounts/views.py
from django.shortcuts import render

# Create your views here.

recommendations/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_GET

from recommendations import models, forms

@require_GET
def top(request):
    styles = models.BeerStyle.objects.all()
    context = {"styles" : styles}

    return render(
        request, "recommendations/top.html",
        context
    )

def regist_style(request):

    if request.method == "POST":
        form = forms.BeerStyleForm(request.POST)
        if form.is_valid():
            style = form.save()
            return redirect(
                detail_style, style_id=style.pk
            )

    else:
        form = forms.BeerStyleForm()
    return render(
        request, "recommendations/regist_style.html",
        {"form" : form}
    )

def detail_style(request, style_id):
    style = get_object_or_404(models.BeerStyle, pk=style_id)
    brands = models.BeerBrand.objects.filter(style__id=style_id)
    context = {"style" : style, "brands" : brands}

    return render(
        request, "recommendations/detail_style.html",
        context
    )

def edit_style(request, style_id):
    style = get_object_or_404(models.BeerStyle, pk=style_id)

    if request.method == "POST":
        form = forms.BeerStyleForm(request.POST, instance=style)
        if form.is_valid():
            style = form.save()
            return redirect(
                detail_style, style_id=style.pk
            )

    else:
        form = forms.BeerStyleForm(instance=style)
    return render(
        request, "recommendations/edit_style.html",
        {"form" : form, "style_id" : style_id}
    )

def regist_brand(request):

    if request.method == "POST":
        form = forms.BeerBrandForm(request.POST)
        if form.is_valid():
            brand = form.save()
            return redirect(
                detail_brand, brand_id=brand.pk
            )

    else:
        form = forms.BeerBrandForm()
    return render(
        request, "recommendations/regist_brand.html",
        {"form" : form}
    )

def detail_brand(request, brand_id):
    brand = get_object_or_404(models.BeerBrand, pk=brand_id)
    reviews = models.BeerReview.objects.filter(review_to__id=brand_id)
    context = {"brand" : brand, "reviews" : reviews}

    return render(
        request, "recommendations/detail_brand.html",
        context
    )

@login_required
def review(request, brand_id):

    try:
        review = models.BeerReview.objects.get(
            review_to__id=brand_id, reviewed_by__id=request.user.id
        )
    except models.BeerReview.DoesNotExist:
        review = None

    if request.method != "POST":
        form = forms.ReviewForm(instance=review)
        return render(
            request,  "recommendations/review.html",
            {"form" : form, "brand_id" : brand_id}
        )

    form = forms.ReviewForm(request.POST, instance=review)

    if form.is_valid:
        review = form.save(commit=False)
        brand = models.BeerBrand.objects.get(pk=brand_id)
        review.review_to = brand
        
    else:
        return render(
            request,  "recommendations/review.html",
            {"form" : form, "brand_id" : brand_id}
        )

    review.reviewed_by = request.user

    review.save()

    return redirect(
        "detail_brand", brand_id=brand_id
    )

accounts/templates/accounts/login.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block main %}
<h2>ログイン</h2>

<form method="POST">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}">
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="ログイン" %}
</form>
{% endblock %}

accounts/templates/accounts/signup.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block main %}
<h2>会員登録</h2>
<form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="登録" %}
</form>
{% endblock %}

app/templates/app/top.html
<!DOCTYPE html>
<html lang="ja" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>DjangoでWebアプリ</title>
  </head>
  <body>
<p>
<a href="{% url 'app:login' %}">ログインへ</a>
</p>
<p>
<a href="{% url 'app:search' %}">検索へ</a>
</p>
<p>
<a href="{% url 'app:overview' %}">一覧へ</a>
</p>
  </body>
</html>

recommendations/templates/recommendations/detail_brand.html
<!DOCTYPE html>
{% extends "base.html" %}

{% block main %}
<h1>ビール銘柄詳細画面</h1>
<div>
  <h2 class="title">{{brand.name}}</h2>
  <ul>
    <li>アルコール度数:{{brand.degree}}</li>
    <li>IBU:{{brand.bitterness}}</li>
    <li>色味:{{brand.color}}</li>
    <li>スタイル:{{brand.style.name}}</li>
  </ul>
  <div class="button-right">
    <a href="{% url 'review' brand.id %}" class="btn btn-primary">
      レビューを書く
    </a>
  </div>
</div>
<div>
  <h2>飲んでみた感想</h2>
  {% if reviews %}
    {% for review in reviews %}
      <div class="card" style="width: 30rem;">
        <div class="card-body">
          {{review.review}}
          <div>
            <small>{{review.reviewed_by}} さんが 
              {% if review.reviewed_at == review.updated_at %}
                {{review.reviewed_at}}に投稿しました
              {% else %}
                {{review.updated_at}}に編集しました
              {% endif %}
            </small>
          </div>
        </div>
      </div>
    {% endfor %}
  {% else %}
    まだ投稿はありません
  {% endif %}
</div>
 {% endblock %}

recommendations/templates/recommendations/detail_style.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}

{% block main %}
<h1>ビールスタイル詳細画面</h1>
<div>
  <h3 class="title">{{style.name}}</h3>
  <ul>
    <li>発祥地:{{style.birth_place}}</li>
    <li>発酵方法:{{style.get_fermentation_display}}</li>
  </ul>
  <div>
    {{style.description}}
  </div>
  <h3>{{style.name}}の銘柄</h3>
  <div>
    {% if brands %}
    <ul>
      {% for brand in brands %}
      <li><a href="{% url 'detail_brand' brand.id %}">{{brand.name}}</a></li>
      {% endfor %}
    </ul>
    {% else %}
    <p>登録されている{{style.name}}の銘柄はありません</p>
    {% endif %}
  </div>
</div>
{% endblock %}

recommendations/templates/recommendations/edit_style.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block main %}
<h1>ビールスタイル編集画面</h1>
<form action="{% url 'edit_style' style_id %}" method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% bootstrap_button button_type="submit" content="保存" %}
</form>
{% endblock %}

recommendations/templates/recommendations/regist_brand.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block main %}
<h1>ビール銘柄登録画面</h1>
<form action="{% url 'regist_brand' %}" method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% bootstrap_button button_type="submit" content="投稿" %}
</form>
{% endblock %}

recommendations/templates/recommendations/regist_style.html
<!DOCTYPE html>
<html lang="ja" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Djangoビールおすすめサイト</title>
  </head>
  <body>
    <h1>ビールスタイル登録画面</h1>
    <form action="{% url 'regist_style' %}" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">登録</button>
    </form>
  </body>
</html>

recommendations/templates/recommendations/review.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block main %}
<h1>ビール銘柄感想投稿画面</h1>
<form action="{% url 'review' brand_id %}" method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% bootstrap_button button_type="submit" content="登録" %}
</form>
{% endblock %}

recommendations/templates/recommendations/top.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}

{% block main %}
<h1>トップ画面</h1>
{% if styles %}
  {% for style in styles %}
  <div class="card" style="width: 18rem;">
    <img src="{% static 'recommendations/NO_IMAGE.png' %}" class="card-img-top">
    <div class="card-body">
      <h5 class="card-title">{{ style.name }}</h5>
      <p class="card-text">{{ style.description }}</p>
      <a href="{% url 'detail_style' style.id %}" class="btn btn-primary">ビアスタイルページへ</a>
    </div>
  </div>
  {% endfor %}
{% else %}
  <h3>ビアスタイルは登録されていません</h3>
{% endif %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load django_bootstrap5 %}
<html lang="ja" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>DjangoでWebアプリ</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" href="{% static 'recommendations/css/style.css' %}">
    {% block extraheader %}{% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-expand flex-md-row navbar-dark bg-dark">
      <div class="container justify-content-between">
        <a href="/" class="navbar-brand">ビール紹介サイト</a>
        <ul class="navbar-nav mr-md-2">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">ログアウト</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">ログイン</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'signup' %}">会員登録</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <main>
      <div class="container">
        {% block main %}{% endblock %}
      </div>
    </main>
  </body>
</html>